services:
  api:
    image: sschonss/api-exec
    container_name: api-exec
    volumes:
      - ./config/.env:/app/config/.env
      - ./public:/app/public
    environment:
      - TZ=America/Sao_Paulo
    command:
      - php
      - index.php